name: Fetch DBT Cloud Artifacts (Hardcoded)

on:
  workflow_dispatch:  # Manually triggered from GitHub UI

jobs:
  fetch-artifacts:
    runs-on: ubuntu-latest

    env:
      DBT_CLOUD_API_KEY: your-dbt-cloud-api-token     # <-- replace this
      ACCOUNT_ID: "12345"                              # <-- replace this
      JOB_ID: "67890"                                  # <-- replace this

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get latest job run ID
      id: get-run
      run: |
        RUN_ID=$(curl -s -H "Authorization: Token $DBT_CLOUD_API_KEY" \
          "https://cloud.getdbt.com/api/v2/accounts/$ACCOUNT_ID/runs/?job_definition_id=$JOB_ID&order_by=-id&limit=1" \
          | jq -r '.data[0].id')
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Create docs folder
      run: mkdir -p dbt_docs

    - name: Download artifacts (manifest.json, catalog.json)
      run: |
        for artifact in manifest.json catalog.json; do
          curl -s -H "Authorization: Token $DBT_CLOUD_API_KEY" \
            -o dbt_docs/$artifact \
            "https://cloud.getdbt.com/api/v2/accounts/$ACCOUNT_ID/runs/$RUN_ID/artifacts/$artifact"
        done

    - name: Commit and push artifacts
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add dbt_docs/
        git commit -m "Update DBT Cloud artifacts [skip ci]" || echo "No changes to commit"
        git push
