name: Fetch DBT Artifacts and Commit

on:
  workflow_dispatch:

jobs:
  fetch-artifacts:
    runs-on: ubuntu-latest

    env:
      DBT_CLOUD_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
      ACCOUNT_ID: "70471823452202"
      JOB_ID: "70471832292458"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Trigger DBT Job
      id: trigger
      run: |
        echo "Triggering DBT Cloud job..."
        RESPONSE=$(curl -s -X POST \
          -H "Authorization: Token $DBT_CLOUD_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{}' \
          "https://cloud.getdbt.com/api/v2/accounts/$ACCOUNT_ID/jobs/$JOB_ID/run/")

        echo "Trigger response: $RESPONSE"
        RUN_ID=$(echo "$RESPONSE" | jq -r '.data.id')

        if [ "$RUN_ID" == "null" ] || [ -z "$RUN_ID" ]; then
          echo "❌ Failed to retrieve RUN_ID. Exiting."
          exit 1
        fi

        echo "✅ RUN_ID=$RUN_ID"
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Wait for dbt job to complete
      run: |
        echo "Waiting for DBT Cloud job run $RUN_ID to complete..."
        while true; do
          STATUS=$(curl -s -H "Authorization: Token $DBT_CLOUD_API_KEY" \
            "https://cloud.getdbt.com/api/v2/accounts/$ACCOUNT_ID/runs/$RUN_ID/" \
            | jq -r '.data.status')

          echo "Current status: $STATUS"
          if [ "$STATUS" == "10" ]; then
            echo "✅ Run $RUN_ID completed successfully."
            break
          elif [ "$STATUS" == "20" ]; then
            echo "❌ Run $RUN_ID failed."
            exit 1
          fi
          sleep 10
        done

    - name: Prepare folder structure
      run: |
        DATE=$(date +'%Y-%m-%d')
        BASE="dbt_docs_generate/${DATE}"
        i=1
        while [ -d "${BASE}_$(printf "%03d" $i)_$RUN_ID" ]; do
          ((i++))
        done
        FINAL_PATH="${BASE}_$(printf "%03d" $i)_$RUN_ID"
        mkdir -p "$FINAL_PATH"
        echo "FINAL_PATH=$FINAL_PATH" >> $GITHUB_ENV

    - name: Download DBT artifacts
      run: |
        for artifact in manifest.json catalog.json index.html; do
          echo "Downloading $artifact..."
          curl -s -H "Authorization: Token $DBT_CLOUD_API_KEY" \
            -o "$FINAL_PATH/$artifact" \
            "https://cloud.getdbt.com/api/v2/accounts/$ACCOUNT_ID/runs/$RUN_ID/artifacts/$artifact"
        done

    - name: Update index.yml
      run: |
        echo "- run_id: $RUN_ID" >> index.yml
        echo "  date: $(date +'%Y-%m-%d')" >> index.yml
        echo "  path: $FINAL_PATH" >> index.yml

    - name: Commit and push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git pull --rebase
        git add dbt_docs_generate/ index.yml

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add DBT artifacts for run ID $RUN_ID [skip ci]"
          git push
        fi
