name: Fetch DBT Artifacts and Commit

on:
  workflow_dispatch:

jobs:
  fetch-artifacts:
    runs-on: ubuntu-latest

    env:
      DBT_CLOUD_API_KEY: dbtc_KcG9T1MgvGk7gWUZlgoh8Qxn5dPARyWyjuMebbVUsF93TtH1LQ
      ACCOUNT_ID: "70471823452202"
      JOB_ID: "70471832292458"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install jq and coreutils
      run: sudo apt-get install -y jq coreutils

    - name: Get latest run ID
      id: get-run
      run: |
        RESPONSE=$(curl -s -H "Authorization: Token $DBT_CLOUD_API_KEY" \
          "https://cloud.getdbt.com/api/v2/accounts/$ACCOUNT_ID/runs/?job_definition_id=$JOB_ID&order_by=-id&limit=1")
        
        RUN_ID=$(echo "$RESPONSE" | jq -r '.data[0].id')

        if [ -z "$RUN_ID" ] || [ "$RUN_ID" == "null" ]; then
          echo "❌ Failed to get a valid RUN_ID."
          exit 1
        fi

        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "✅ Got RUN_ID: $RUN_ID"

    - name: Set date-based folder name
      id: set-folder
      run: |
        DATE=$(date +'%Y-%m-%d')
        FOLDER_NAME="${DATE}_${RUN_ID}"
        echo "FOLDER_NAME=$FOLDER_NAME" >> $GITHUB_ENV
        echo "✅ Folder name: $FOLDER_NAME"

    - name: Create docs folder
      run: mkdir -p dbt_docs/${{ env.FOLDER_NAME }}

    - name: Download DBT artifacts
      run: |
        for artifact in manifest.json catalog.json; do
          echo "Downloading $artifact..."
          curl -s -H "Authorization: Token $DBT_CLOUD_API_KEY" \
            -o "dbt_docs/${{ env.FOLDER_NAME }}/$artifact" \
            "https://cloud.getdbt.com/api/v2/accounts/$ACCOUNT_ID/runs/${{ env.RUN_ID }}/artifacts/$artifact"
        done

    - name: Commit and push to repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git pull --rebase origin main

        git add dbt_docs/

        if git diff --cached --quiet; then
          echo "✅ No changes to commit"
        else
          git commit -m "Add DBT artifacts for run ID $RUN_ID on $FOLDER_NAME [skip ci]"
          git push
        fi
