name: Fetch DBT Artifacts and Commit

on:
  workflow_dispatch:

jobs:
  fetch-artifacts:
    runs-on: ubuntu-latest

    env:
      DBT_CLOUD_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
      ACCOUNT_ID: "70471823452202"
      JOB_ID: "70471832292458"
      RUN_ID: "70471832298282"  # <-- Hardcoded RUN_ID

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    # Removed the "Get latest run ID" step

    - name: Create docs folder
      run: mkdir -p docs

    - name: Download DBT artifacts
      run: |
        for artifact in manifest.json catalog.json index.html; do
         echo "Downloading $artifact..."
         curl -s -H "Authorization: Token $DBT_CLOUD_API_KEY" \
           -o "docs/$artifact" \
           "https://cloud.getdbt.com/api/v2/accounts/$ACCOUNT_ID/runs/$RUN_ID/artifacts/$artifact"
        done

    - name: Commit and push to repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git stash --include-untracked
        git pull --rebase origin main
        git stash pop || true  # continue even if stash pop has conflicts or nothing to apply

        git add docs/

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update DBT Cloud artifacts [skip ci]"
          git push
        fi

