name: Fetch DBT Artifacts and Commit

on:
  workflow_dispatch:

jobs:
  fetch-artifacts:
    runs-on: ubuntu-latest

    env:
      DBT_CLOUD_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
      ACCOUNT_ID: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
      JOB_ID: ${{ secrets.DBT_CLOUD_JOB_ID }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Create docs folder
      run: mkdir -p docs

    - name: Download DBT artifacts
      run: |
        for artifact in manifest.json catalog.json index.html; do
          echo "Downloading $artifact..."
          RESPONSE=$(curl -s -H "Authorization: Token $DBT_CLOUD_API_KEY" \
            "https://cloud.getdbt.com/api/v2/accounts/$ACCOUNT_ID/runs/$JOB_ID/artifacts/$artifact")

          echo "$RESPONSE" > "docs/$artifact"

          STATUS_CODE=$(echo "$RESPONSE" | jq -r '.status.code // empty')

          if [[ "$STATUS_CODE" == "401" ]]; then
            echo "⚠️ Failed to download $artifact — Unauthorized (401). Check if the artifact exists or token has correct permissions."
          else
            echo "✅ Successfully downloaded $artifact"
          fi
        done

    - name: Commit and push to repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git stash --include-untracked
        git pull --rebase origin main
        git stash pop || true

        git add docs/

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update DBT Cloud artifacts [skip ci]"
          git push
        fi
