name: Trigger DBT Cloud Job

on:
  workflow_dispatch:

jobs:
  trigger-dbt-job:
    runs-on: ubuntu-latest

    env:
      DBT_CLOUD_API_KEY: ${{ secrets.DBT_CLOUD_API_KEY }}
      ACCOUNT_ID: "70471823452202"
      JOB_ID: "70471832292458"

    steps:
      - name: Trigger DBT Cloud Job
        id: trigger
        run: |
          echo "Triggering DBT Cloud job $JOB_ID..."

          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Token $DBT_CLOUD_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"cause": "Triggered from GitHub Actions"}' \
            https://cloud.getdbt.com/api/v2/accounts/$ACCOUNT_ID/jobs/$JOB_ID/run/)

          echo "$RESPONSE"
          
          RUN_ID=$(echo "$RESPONSE" | jq -r '.data.id')
          
          if [[ "$RUN_ID" == "null" ]]; then
            echo "❌ Failed to trigger DBT job. Check credentials and job settings."
            exit 1
          fi

          echo "✅ DBT job triggered with RUN_ID=$RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Wait for DBT Cloud Job to Finish
        run: |
          echo "Waiting for DBT Cloud run $RUN_ID to complete..."

          while true; do
            STATUS=$(curl -s -H "Authorization: Token $DBT_CLOUD_API_KEY" \
              https://cloud.getdbt.com/api/v2/accounts/$ACCOUNT_ID/runs/$RUN_ID/ \
              | jq -r '.data.status')

            echo "Current status: $STATUS"

            # DBT status codes:
            # 10: Success, 20: Error, 30: Cancelled
            if [[ "$STATUS" == "10" ]]; then
              echo "✅ DBT run succeeded"
              break
            elif [[ "$STATUS" == "20" || "$STATUS" == "30" ]]; then
              echo "❌ DBT run failed or was cancelled"
              exit 1
            else
              sleep 10
            fi
          done
